### ISSUE TITLE
EDA Connections

### ISSUE THREAD

**Issue by allisonletts** [SFDO-Community-Sprints/OutboundFunds#3]
How should EDA work with Outbound Funds?

**Comment by Nickers3** [comment]
EDA Data Model: https://powerofus.force.com/s/article/EDA-Entity-Relationship-Diagram

**Comment by allisonletts** [comment]
This was addressed [in the Wiki as part of the Convo History](https://github.com/SFDO-Community-Sprints/OutboundFunds/wiki/Conversation-History#what-did-we-talk-about-on-923). It ended up being an entry point into a GAU replacement object. We're functionally done with this topic.

**Comment by Nickers3** [comment]
Here is a prototype of the GAU build

![image](https://user-images.githubusercontent.com/11097954/94070140-51b6d300-fdb7-11ea-9db4-5d80c884f5ee.png)

**Comment by Nickers3** [comment]
Created new repo to track new package: https://github.com/Nickers3/OutboundFundsGAU/pull/1
